# Default values for helm_chart01.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kodekloud/simple-webapp
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "green"

service:
  name: my-service
  type: NodePort
  port: 8080
  nodePort: 30007

data:
  name: demo-app
  labels:
    app: nginx
  port:
    number: 8080
    name: http
    protocol: TCP
