name: CI/CD

on:
  push:
    branches:
      - production
      - staging
      - development  # Listen for pushes to the production, staging, and development branches

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEV_VALUES_FILE: '/dev-values.yaml'
      STAGING_VALUES_FILE: '/staging-values.yaml'
      PROD_VALUES_FILE: '/prod-values.yaml'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.14.2'

      - name: Test Helm commands (no actual deployment)
        run: |
          echo "Testing Helm commands..."
          echo "Deploying to dev environment (simulated):"
          cat $DEV_VALUES_FILE  # Display the content of the dev values file
          echo "Deploying to staging environment (simulated):"
          cat $STAGING_VALUES_FILE  # Display the content of the staging values file
          echo "Deploying to production environment (simulated):"
          cat $PROD_VALUES_FILE  # Display the content of the production values file
