name: CI/CD

on:
  push:
    branches:
      - production
      - staging
      - development  # Listen for pushes to the production, staging, and development branches

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEV_VALUES_FILE: ./dev-values.yaml
      STAGING_VALUES_FILE: ./staging-values.yaml
      PROD_VALUES_FILE: ./prod-values.yaml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.14.2'

      - name: Debug
        run: |
          pwd
          ls -la

      - name: Deploy to dev
        if: github.ref == 'refs/heads/development'  # Condition to deploy only on the development branch
        # run: |
        #   helm upgrade --install my-app-dev ./helm-chart-demo-app \
        #     --values $DEV_VALUES_FILE
        run: |
          echo "Testing Helm commands..."
          echo "Deploying to dev environment (simulated):"
          cat $DEV_VALUES_FILE  # Display the content of the dev values file

      - name: Deploy to staging
        if: github.ref == 'refs/heads/staging'  # Condition to staging only on the staging branch
        # run: |
        #   # helm upgrade --install my-app-staging ./helm-chart-demo-app \
        #   #   --values $STAGING_VALUES_FILE
        run: |
          echo "Testing Helm commands..."
          echo "Deploying to staging environment (simulated):"
          cat $STAGING_VALUES_FILE  # Display the content of the staging values file

      - name: Deploy to production
        if: github.ref == 'refs/heads/production'  # Condition to deploy only on the production branch
        # run: |
        #   helm upgrade --install my-app-prod ./helm-chart-demo-app \
        #     --values $PROD_VALUES_FILE
        run: |
          echo "Testing Helm commands..."
          echo "Deploying to production environment (simulated):"
          cat $PROD_VALUES_FILE  # Display the content of the production values file
